{% set name = "pandaSDMX" %}
<<<<<<< Updated upstream
{% set version = "1.0.1" %}
=======
{% set version = "1.1.0" %}
>>>>>>> Stashed changes

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
<<<<<<< Updated upstream
  sha256: ec85a6606635ebd02af9f6df535faf7e38b398f302429e27f70ecf30de80569e
=======
  sha256: d225cfef0e7a9f0a76b47f099edbb18af2ae8c549908899831a54af5f9edd897
>>>>>>> Stashed changes

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - flit >=2.3
    - pip
  run:
    - python >=3.7
    - lxml >=3.6
    - pandas >=0.24
    - pydantic >=1.1
    - requests >=2.7

test:
  imports:
    - pandasdmx
    - pandasdmx.reader.sdmxml
    - pandasdmx.writer

about:
  home: https://github.com/dr-leo/pandasdmx
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Statistical Data and Metadata eXchange (SDMX) for the Python data ecosystem
  doc_url: https://pandasdmx.readthedocs.io/
  dev_url: https://github.com/dr-leo/pandasdmx

extra:
  recipe-maintainers:
    - dr-leo
