{% set name = "pandaSDMX" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c51145383970c6e0cbef959f09503d8d2af8d1a2c482226b508c29015c045e83

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9.6, <3.12
    - flit >=3.5
    - pip
  run:
    - python >=3.9.6, < 3.12
    - lxml >=4.9
    - pandas >=1.3
    - pydantic >=1.9.2, <2
    - requests >=2.28
    - appdirs >=1.4

test:
  imports:
    - pandasdmx
    - pandasdmx.reader.sdmxml
    - pandasdmx.writer

about:
  home: https://github.com/dr-leo/pandasdmx
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Statistical Data and Metadata eXchange (SDMX) for the Python data ecosystem
  doc_url: https://pandasdmx.readthedocs.io/
  dev_url: https://github.com/dr-leo/pandasdmx

extra:
  recipe-maintainers:
    - dr-leo
