{% set name = "pandaSDMX" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eee87d14c8e1982455e3e49a9ddc95c75ebf8a6d4ea3653dd000666977b98d22

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7, <4
    - flit >=2.3
    - pip
  run:
    - python >=3.7.3, <4
    - lxml >=3.6
    - pandas >=0.25
    - pydantic >=1.7.1, <1.8
    - requests >=2.20

test:
  imports:
    - pandasdmx
    - pandasdmx.reader.sdmxml
    - pandasdmx.writer

about:
  home: https://github.com/dr-leo/pandasdmx
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Statistical Data and Metadata eXchange (SDMX) for the Python data ecosystem
  doc_url: https://pandasdmx.readthedocs.io/
  dev_url: https://github.com/dr-leo/pandasdmx

extra:
  recipe-maintainers:
    - dr-leo
