{% set name = "pandaSDMX" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ffa4459a843943b10e7136a1a45b8dcafaf22985cec1d30253b09eff0fc894ac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7, <4
    - flit >=2.5
    - pip
  run:
    - python >=3.7.6, <4
    - lxml >=4.1
    - pandas >=1.1
    - pydantic >=1.8.1, <2
    - requests >=2.20

test:
  imports:
    - pandasdmx
    - pandasdmx.reader.sdmxml
    - pandasdmx.writer

about:
  home: https://github.com/dr-leo/pandasdmx
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Statistical Data and Metadata eXchange (SDMX) for the Python data ecosystem
  doc_url: https://pandasdmx.readthedocs.io/
  dev_url: https://github.com/dr-leo/pandasdmx

extra:
  recipe-maintainers:
    - dr-leo
